### ISSUE TITLE
Empty server params

### ISSUE THREAD

**Issue by MidnightDesign** [zendframework/zend-psr7bridge#14]
Is there a reason why [the server params aren't passed](https://github.com/zendframework/zend-psr7bridge/blob/master/src/Psr7ServerRequest.php#L76) to the PSR-7 server request? Should I open a PR?

**Comment by weierophinney** [comment]
Only because they are not part of the zend-http request. Would you be interesting/willing to create a PR to add them?

**Comment by MidnightDesign** [comment]
`Zend\Http\Request` doesn't know about them, but `Zend\Http\PhpEnvironment\Request` does. I would just add something like `$zendRequest instanceof Zend\Http\PhpEnvironment\Request ? $zendRequest->getServer() : []`.

**Comment by MidnightDesign** [comment]
I've opened #15.
