### ISSUE TITLE
Erroneous upload breaks request bridge

### ISSUE THREAD

**Issue by Pittiplatsch** [zendframework/zend-psr7bridge#21]
`\Zend\Psr7Bridge\Psr7ServerRequest::convertUploadedFiles()` tries to access `$upload->getStream()` which fails on `$upload->getError() !== UPLOAD_ERR_OK` - see `\Zend\Diactoros\UploadedFile::getStream()`.

**Comment by froschdesign** [comment]
@Pittiplatsch 
Can you provide a simple code example or unit test to reproduce the problem? Thanks!

**Comment by Pittiplatsch** [comment]
I'm just about to fix it. PR follows.

Problem is simple to reproduce:
Create a form with two upload fields, but fill only one upon upload.
The second (empty) one will lead to Upload error = 4 which prevents `$upload->getStream()` from working as expected...

**Comment by froschdesign** [comment]
> PR follows.

Please include an unit test, that would be great.

>Problem is simple to reproduce:

Don't get me wrong we want to help, but we can not write all the code to reproduce the problem for every single issue. Help us and we help you. 😃 
Thanks!

**Comment by Pittiplatsch** [comment]
See https://github.com/zendframework/zend-psr7bridge/pull/23 for fix including unit test :)

**Comment by ezimuel** [comment]
Fixed with PR #23.
