### ISSUE TITLE
does not convert uploaded files correctly

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-psr7bridge#6]
here: https://github.com/zendframework/zend-psr7bridge/blob/master/src/Psr7ServerRequest.php#L112

``` php
...
'tmp_name' => $upload->getStream()
...
```

this should be `string` not `StreamInterface` because of that zend-validator almost all file validators  does not work. Also:

``` php
// do request with 1 file
$files = $request->getUploadedFiles(); // returns array with 1 file
$request = Psr7ServerRequest::toZend($request);
$request2 = Psr7ServerRequest::fromZend($request);
$files2 = $request2->getUploadedFiles(); // return empty array
```

I understand that PSR7 does not have method in interface to retrieve `tmp_name` but maybe some kind of workaround could be used?

**Comment by svycka** [comment]
ok one part is fixed with https://github.com/zendframework/zend-psr7bridge/pull/7

who can explain what is this: https://github.com/zendframework/zend-psr7bridge/blob/master/src/Psr7ServerRequest.php#L127

**Comment by svycka** [comment]
updated #7 if everything is ok should fix both problems. @weierophinney is it ok?

**Comment by svycka** [comment]
also @ezimuel can you confirm this is ok since you introduced this zend to psr7 conversion. 
Also maybe you remember what this https://github.com/zendframework/zend-psr7bridge/blob/master/src/Psr7ServerRequest.php#L127 should do?

``` php
if (!isset($files['file'])) {
    return [];
}
```

**Comment by MidnightDesign** [comment]
I just stumbled upon the same issue. `if (!isset($files['file']))` breaks it for me.
